### ISSUE TITLE
Throw the Valve's module factory away (with compatibility preservation)?

### ISSUE THREAD

**Issue by BlackPhrase** [BlackPhrase/magenta#22]
Our only requirement is to support game and client dlls
It doesn't matter how this support or other engine parts are implemented
It looks like this crap came out unportable but I'm still unsure about that
If this would be confirmed then I'll probably get rid of the interface.cpp (it violates the GPL terms anyway) and will be using something more portable

**Comment by Sh1ft0x0EF** [comment]
Works flawlessly without a destructor in vtable!
Amazing!
F*cking piece of shit

**Comment by Sh1ft0x0EF** [comment]
Need to clarify some things

First:
* CS:CZ ClientDLL requires the ICareerUI interface via the cl_enginefuncs_t structure in order to work;
* Either engine->cldll or clientdll->engine interfaces contains the function to access the ClientFactory which requires the module factory;
* Internal Valve mods probably requires some VGUI2 interfaces;
* We shouldn't use the Valve's module factory in its original state for our native interfaces anymore (because of low portability, ABI issues (hope dies last) and license incompatibility);
* In case it would be required we could provide some MSVC plugin-mediator that will provide the needed interface to MSVC mod dll (best case scenario);

Second:
* Most community mods don't have access to this functionality so they work fine even without the module factory (Xash does support all (or at least most) of them);
* Any ClientDLL could provide the optional IClientGameExports interface implementation needed for the GameUI module (it will use it's internal version otherwise);
